#!/usr/bin/env bash
# One command: re-stamp branding on main -> optional build.
#
#   bash refresh-brand.sh            # re-stamp + commit on main
#   bash refresh-brand.sh --build    # same, then rebuild the frontend image
#
# Branch model in the Suna repo:
#   main : feature commits + squashed chore(brand) stamp commits (build here)
# (The old local-dev/deploy two-branch model is retired: local-dev tracks a
# 574-commit-stale upstream ref and must NOT be checked out.)
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "$DIR/config.sh"
REPO="$SUNA_REPO"

cd "$REPO"
BRANCH="$(git branch --show-current)"
echo "[refresh] branch: $BRANCH"
if [ "$BRANCH" != "main" ]; then
  echo "[refresh] ERROR: expected branch 'main' (branding commits live there)." >&2
  echo "[refresh] Refusing to touch '$BRANCH' -- 'git checkout main' first." >&2
  exit 1
fi

echo "[refresh] fetching upstream/main (informational)..."
git fetch upstream main || echo "[refresh] WARN: upstream fetch failed, stamping anyway"

echo "[refresh] re-stamping branding..."
bash "$DIR/apply.sh"
git add -A
git commit -m 'chore(brand): Dosco stamp (generated by dosco-brand apply.sh)' \
  || echo "[refresh] no branding changes to commit"

if [ "${1:-}" = "--build" ]; then
  bash "$DIR/build-frontend.sh"
else
  echo "[refresh] main stamped. Build with: bash $DIR/build-frontend.sh"
fi
echo "[refresh] done."
