#!/usr/bin/env bash
# One command: sync upstream → refresh the deploy branch → optional build.
#
#   bash refresh-brand.sh            # fetch + rebase + rebrand deploy branch
#   bash refresh-brand.sh --build    # same, then rebuild the frontend image
#
# Branch model in the Suna repo:
#   local-dev : upstream/main + local feature commits (rebases cleanly)
#   deploy    : local-dev + ONE squashed brand-stamp commit (build from here)
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "$DIR/config.sh"
REPO="$SUNA_REPO"

cd "$REPO"
echo "[refresh] branch: $(git branch --show-current)"
[ "$(git branch --show-current)" = "local-dev" ] || git checkout local-dev

echo "[refresh] fetching upstream/main..."
git fetch upstream main

echo "[refresh] rebasing local commits onto upstream/main..."
git rebase upstream/main || {
  echo "[refresh] CONFLICTS — resolve them, 'git add', then 'git rebase --continue'," >&2
  echo "[refresh] then run refresh-brand.sh again." >&2
  exit 1
}

echo "[refresh] refreshing deploy branch (reset to local-dev + re-stamp)..."
git checkout deploy
git reset --hard local-dev
bash "$DIR/apply.sh"
git add -A
git commit -m 'chore(brand): Dosco stamp (generated by dosco-brand apply.sh)' \
  || echo "[refresh] no branding changes to commit"

if [ "${1:-}" = "--build" ]; then
  bash "$DIR/build-frontend.sh"
else
  echo "[refresh] deploy branch ready. Build with: bash $DIR/build-frontend.sh"
fi
git checkout local-dev
echo "[refresh] done."